#!/usr/bin/env python3
"""
inspect_xlsx.py — Reusable auditor for WSS questionnaire XLSX files.

Usage:
    python utils/inspect_xlsx.py                          # default file + sheet from strings.xml
    python utils/inspect_xlsx.py path/to/file.xlsx        # specific file, all sheets
    python utils/inspect_xlsx.py path/to/file.xlsx Sheet1 # specific file + sheet
    python utils/inspect_xlsx.py --list                   # list sheets in default file

Modes (pass as last positional arg after sheet, or use --mode):
    audit    (default) run full structural audit for parser compatibility
    dump     print all rows with their parsed columns
    search   --search TERM   grep all cells for a string (case-insensitive)
    schema   print column names and their positions
"""

import sys
import os
import re
import argparse

try:
    import openpyxl
except ImportError:
    sys.exit("openpyxl not installed. Run: pip install openpyxl")

# ---------------------------------------------------------------------------
# Defaults (mirrors strings.xml)
# ---------------------------------------------------------------------------
DEFAULT_FILE  = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main",
                             "assets", "Survey_Questionnaire_26050601.xlsx")
DEFAULT_SHEET = "Pumping Based 26051402"

# Known answer types accepted by QuestionnaireParser / QuestionFragment
KNOWN_TYPES = {
    "TEXT", "NUMBER", "MULTIPLE_CHOICE_SINGLE", "MULTIPLE_CHOICE_MULTI",
    "YES_NO", "DATE_FULLDATE", "DATE_YEAR", "DATE_YEAR_MONTH",
    "TIME", "DATE_TIME", "DURATION", "LOCATION", "COMPOUND",
}

# Types whose answer_options are fully generated by the parser (should be empty in sheet)
PARSER_GENERATED_OPTIONS = {"YES_NO"}

# Valid sub-field types inside COMPOUND
COMPOUND_SUBTYPES = {
    "TEXT", "NUMBER", "MULTIPLE_CHOICE_SINGLE", "MULTIPLE_CHOICE_MULTI",
    "DATE_FULLDATE", "DATE_YEAR", "DATE_YEAR_MONTH", "TIME", "DATE_TIME", "LOCATION",
}

# Valid NUMBER sub-types
NUMBER_SUBTYPES = {"INTEGER", "DECIMAL", "PERCENTAGE"}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def cv(cell):
    """Return cell value as stripped string, or '' if None."""
    v = cell.value
    return str(v).strip() if v is not None else ""


def load_sheet(path, sheet_name):
    wb = openpyxl.load_workbook(path, read_only=True, data_only=True)
    if sheet_name not in wb.sheetnames:
        print(f"[ERROR] Sheet '{sheet_name}' not found.")
        print(f"        Available sheets: {wb.sheetnames}")
        sys.exit(1)
    return wb[sheet_name]


def get_col_map(ws):
    """Return {column_name_lower: col_index} from header row."""
    headers = {}
    for cell in next(ws.iter_rows(min_row=1, max_row=1)):
        if cell.value:
            headers[str(cell.value).strip().lower()] = cell.column - 1
    return headers


def get_rows(ws, col_map):
    """Yield dicts for each data row (skip header)."""
    rows = list(ws.iter_rows(min_row=2, values_only=False))
    for row in rows:
        vals = [cv(c) for c in row]
        d = {k: (vals[i] if i < len(vals) else "") for k, i in col_map.items()}
        d["_row"] = row[0].row
        yield d


# ---------------------------------------------------------------------------
# Audit checks
# ---------------------------------------------------------------------------

def check_unknown_type(row, issues):
    t = row.get("answer_type", "")
    if t and t not in KNOWN_TYPES:
        issues.append((row["_row"], row.get("id","?"),
                       f"Unknown answer_type '{t}'"))


def check_parser_generated_options(row, issues):
    t = row.get("answer_type", "")
    opts = row.get("answer_options", "")
    if t in PARSER_GENERATED_OPTIONS and opts:
        issues.append((row["_row"], row.get("id","?"),
                       f"{t} has non-empty answer_options '{opts}' (parser ignores it)"))


def check_compound_subfields(row, issues):
    if row.get("answer_type") != "COMPOUND":
        return
    opts = row.get("answer_options", "")
    if not opts:
        issues.append((row["_row"], row.get("id","?"),
                       "COMPOUND question has empty answer_options"))
        return

    # Trailing pipe
    if opts.endswith("|"):
        issues.append((row["_row"], row.get("id","?"),
                       f"COMPOUND options has trailing '|': '{opts[-30:]}'"))

    fields = opts.split("|")
    for fdef in fields:
        tokens = fdef.split(":")
        if len(tokens) < 2:
            issues.append((row["_row"], row.get("id","?"),
                           f"COMPOUND sub-field missing type token: '{fdef}'"))
            continue
        label, subtype = tokens[0], tokens[1].strip()
        # Leading space in label
        if tokens[0] != tokens[0].strip():
            issues.append((row["_row"], row.get("id","?"),
                           f"COMPOUND sub-field label has whitespace: '{fdef}'"))
        if subtype not in COMPOUND_SUBTYPES:
            issues.append((row["_row"], row.get("id","?"),
                           f"Unknown COMPOUND sub-field type '{subtype}' in '{fdef}'"))
        # NUMBER without NUMBER keyword (e.g. label:INTEGER:...)
        if subtype in NUMBER_SUBTYPES:
            issues.append((row["_row"], row.get("id","?"),
                           f"COMPOUND sub-field '{label}' uses '{subtype}' directly — "
                           f"should be 'NUMBER:{subtype}' e.g. '{label}:NUMBER:{subtype}'"))
        # NUMBER: check sub-type token
        if subtype == "NUMBER" and len(tokens) >= 3:
            nsubtype = tokens[2].strip()
            if nsubtype and nsubtype not in NUMBER_SUBTYPES | {""}:
                # could be a unit — only flag if it looks like a type keyword
                if nsubtype.upper() in {"INT", "FLOAT", "STR", "BOOL"}:
                    issues.append((row["_row"], row.get("id","?"),
                                   f"NUMBER sub-type '{nsubtype}' not recognised; "
                                   f"use INTEGER / DECIMAL / PERCENTAGE"))


def check_options_for_mcs(row, issues):
    t = row.get("answer_type", "")
    opts = row.get("answer_options", "")
    if t in ("MULTIPLE_CHOICE_SINGLE", "MULTIPLE_CHOICE_MULTI"):
        if not opts:
            issues.append((row["_row"], row.get("id","?"),
                           f"{t} has no answer_options (no choices defined)"))


def check_number_format(row, issues):
    if row.get("answer_type") != "NUMBER":
        return
    opts = row.get("answer_options", "")
    if not opts:
        return
    tokens = opts.split("|")
    first = tokens[0].strip().upper()
    if first and first not in NUMBER_SUBTYPES:
        issues.append((row["_row"], row.get("id","?"),
                       f"NUMBER first token '{first}' is not a recognised sub-type "
                       f"(INTEGER/DECIMAL/PERCENTAGE); it will be treated as a unit label"))


def check_parent_trigger(row, issues, id_set):
    pid = row.get("parent_id", "")
    tv  = row.get("trigger_value", "")
    if pid and pid not in id_set:
        issues.append((row["_row"], row.get("id","?"),
                       f"parent_id={pid} does not match any question id in this sheet"))
    if pid and not tv:
        issues.append((row["_row"], row.get("id","?"),
                       f"has parent_id={pid} but no trigger_value"))
    if tv and not pid:
        issues.append((row["_row"], row.get("id","?"),
                       f"has trigger_value='{tv}' but no parent_id"))


def run_audit(ws, col_map, verbose=False):
    rows = list(get_rows(ws, col_map))
    id_set = {r.get("id","") for r in rows if r.get("id","")}
    issues = []

    for row in rows:
        check_unknown_type(row, issues)
        check_parser_generated_options(row, issues)
        check_compound_subfields(row, issues)
        check_options_for_mcs(row, issues)
        check_number_format(row, issues)
        check_parent_trigger(row, issues, id_set)

    if not issues:
        print(f"[OK] No issues found across {len(rows)} rows.")
    else:
        print(f"[ISSUES] {len(issues)} problem(s) found:\n")
        for (rnum, rid, msg) in issues:
            print(f"  Row {rnum:>4}  id={rid:<6}  {msg}")
    return issues


# ---------------------------------------------------------------------------
# Dump mode
# ---------------------------------------------------------------------------

def run_dump(ws, col_map, max_rows=None):
    rows = list(get_rows(ws, col_map))
    if max_rows:
        rows = rows[:max_rows]
    width = max(len(k) for k in col_map) + 2
    for r in rows:
        print(f"\n--- Row {r['_row']} ---")
        for k in col_map:
            v = r.get(k, "")
            if v:
                print(f"  {k:<{width}}: {v}")


# ---------------------------------------------------------------------------
# Search mode
# ---------------------------------------------------------------------------

def run_search(ws, col_map, term):
    term_l = term.lower()
    hits = 0
    for row in get_rows(ws, col_map):
        matched_cols = [(k, v) for k, v in row.items()
                        if k != "_row" and term_l in v.lower()]
        if matched_cols:
            hits += 1
            print(f"\nRow {row['_row']}  id={row.get('id','?')}")
            for k, v in matched_cols:
                print(f"  {k}: {v}")
    if hits == 0:
        print(f"No matches for '{term}'.")
    else:
        print(f"\n{hits} row(s) matched.")


# ---------------------------------------------------------------------------
# Schema mode
# ---------------------------------------------------------------------------

def run_schema(ws):
    for cell in next(ws.iter_rows(min_row=1, max_row=1)):
        if cell.value:
            print(f"  Col {cell.column:>3} ({cell.column_letter})  {cell.value}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("file",   nargs="?", default=DEFAULT_FILE,
                   help="Path to XLSX file")
    p.add_argument("sheet",  nargs="?", default=DEFAULT_SHEET,
                   help="Sheet name")
    p.add_argument("--list", action="store_true",
                   help="List sheet names and exit")
    p.add_argument("--mode", choices=["audit","dump","search","schema"],
                   default="audit", help="Operation mode (default: audit)")
    p.add_argument("--search", metavar="TERM",
                   help="Search term (implies --mode search)")
    p.add_argument("--max-rows", type=int, default=None,
                   help="Limit rows printed in dump mode")
    p.add_argument("--verbose", action="store_true")

    args = p.parse_args()

    if not os.path.isfile(args.file):
        sys.exit(f"File not found: {args.file}")

    wb = openpyxl.load_workbook(args.file, read_only=True, data_only=True)

    if args.list:
        print("Sheets:")
        for s in wb.sheetnames:
            print(f"  {s}")
        return

    if args.sheet not in wb.sheetnames:
        print(f"Sheet '{args.sheet}' not found. Available:")
        for s in wb.sheetnames:
            print(f"  {s}")
        sys.exit(1)

    ws = wb[args.sheet]
    col_map = get_col_map(ws)

    if not col_map:
        sys.exit("Could not read header row.")

    mode = "search" if args.search else args.mode

    print(f"File : {os.path.basename(args.file)}")
    print(f"Sheet: {args.sheet}")
    print(f"Mode : {mode}\n")

    if mode == "audit":
        run_audit(ws, col_map, verbose=args.verbose)
    elif mode == "dump":
        run_dump(ws, col_map, max_rows=args.max_rows)
    elif mode == "search":
        run_search(ws, col_map, args.search or "")
    elif mode == "schema":
        run_schema(ws)


if __name__ == "__main__":
    main()
